# Generated by Django 3.1.4 on 2020-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Task_id',
                'verbose_name_plural': 'Task_ids',
            },
        ),
    ]
